### PR TITLE
fix trigger changed logic

### LINKED ISSUE #2839: TS Burned All Data engine stop
when TS burn itself, then the engine stops ... 
i checked 3 latest firmware releases ...
New Bitmap Image (2) (1)

### PR DESCRIPTION
**Pull request by mck1117**
You can't compare arrays by value in c++.

Fixes #2839

### CODE REVIEW

File: firmware/controllers/trigger/trigger_central.cpp [hunk 1]
```diff
@@ -686,28 +686,32 @@ static void resetRunningTriggerCounters() {
...
-		isConfigurationChanged(trigger.type) ||
-		isConfigurationChanged(ambiguousOperationMode) ||
-		isConfigurationChanged(useOnlyRisingEdgeForTrigger) ||
-		isConfigurationChanged(globalTriggerAngleOffset) ||
-		isConfigurationChanged(trigger.customTotalToothCount) ||
-		isConfigurationChanged(trigger.customSkippedToothCount) ||
-		isConfigurationChanged(triggerInputPins[0]) ||
-		isConfigurationChanged(triggerInputPins[1]) ||
-		isConfigurationChanged(triggerInputPins[2]) ||
-		isConfigurationChanged(vvtMode) ||
```
Comment (mck1117) [inline firmware/controllers/trigger/trigger_central.cpp:707]: This line, `isConfigurationChanged(vvtMode)`, was the problem.  If you compare arrays with identical contents, they will compare not equal since it will actually compare the _pointer_, not the values within the array.

**Comment by rusefillc** [comment]
Exciting! What are we missing to have this in master? :)

**Comment by mck1117** [comment]
It seems to have helped, but not 100% fixed...
