### PR TITLE
fix icu trigger polarity

### LINKED ISSUE #1176: BUG HW trigger inputs got inverted...
I think I've seen stuff inverted but I just decided to ignore it.

And now we have a complaint around https://rusefi.com/forum/viewtopic.php?p=35616#p35616

### PR DESCRIPTION
**Pull request by mck1117**
fix #1176

### CODE REVIEW

File: firmware/development/logic_analyzer.cpp [hunk 1]
```diff
@@ -110,14 +110,12 @@ static void initWave(const char *name, int index) {
 	if (brainPin == GPIO_UNASSIGNED)
 		return;
 
-	bool mode = CONFIG(logicAnalyzerMode)[index];
```
Comment (mck1117) [inline firmware/development/logic_analyzer.cpp]: there wasn't actually any way to set this - should probably remove and save the config space.

**Comment by mck1117** [comment]
Does the correct thing now:
image
