### PR TITLE
Fix prepareEventAngles for symmetrical crank triggers

### LINKED ISSUE #2958: NB2 hellen-72-rev-d something is off
image

note very unexpected spark scheduling see https://rusefi.com/forum/viewtopic.php?p=41519#p41519

### LINKED ISSUE #2980: NB2 trigger shape does not seem to match JimStim
JimStim does not approve of rusEFI trigger shape definition? note errors in coil scheduling

depending on RPM we either have one coil event not even or just totally not present

image

image

### PR DESCRIPTION
**Pull request by mck1117**
fixes #2980
probably also fixes #2958

### CODE REVIEW

**Comment by mck1117** [comment]
Look at this beautiful even spacing!

image

File: firmware/controllers/trigger/trigger_decoder.cpp [hunk 1]
```diff
@@ -170,22 +170,38 @@ void prepareEventAngles(TriggerWaveform *shape,
...
 		if (eventIndex == 0) {
 			// explicit check for zero to avoid issues where logical zero is not exactly zero due to float nature
 			details->eventAngles[0] = 0;
 			// this value would be used in case of front-only
 			details->eventAngles[1] = 0;
 		} else {
-			assertAngleRange(shape->triggerShapeSynchPointIndex, "triggerShapeSynchPointIndex", CUSTOM_TRIGGER_SYNC_ANGLE2);
-			unsigned int triggerDefinitionCoordinate = (shape->triggerShapeSynchPointIndex + eventIndex) % length;
-			efiAssertVoid(CUSTOM_TRIGGER_CYCLE, engine->engineCycleEventCount != 0, "zero engineCycleEventCount");
-			int triggerDefinitionIndex = triggerDefinitionCoordinate >= shape->privateTriggerDefinitionSize ? triggerDefinitionCoordinate - shape->privateTriggerDefinitionSize : triggerDefinitionCoordinate;
```
Comment (mck1117) [inline firmware/controllers/trigger/trigger_decoder.cpp:183]: this line was the problem - should've been plain modulo instead
