### PR TITLE
cranking base fuel and cranking coolant multiplier progress

### LINKED ISSUE #8037: Remove "Cranking Fuel Multiplier" curve
**Describe the bug**
There is no need  for this curve since CLT is baked into "Cranking Base Fuel"  now

**To Reproduce**
1. Go to Cranking
2. Click on Cranking Fuel Multiplier
3. Set to all 1.00 because fuel amount is compensated in normal craning fuel table

Image

### PR DESCRIPTION
**Pull request by FDSoftware**
part of : [cranking base fuel and cranking coolant multiplier #7567](https://github.com/rusefi/rusefi/issues/7567)
resolves #8037 [Remove "Cranking Fuel Multiplier" curve](https://github.com/rusefi/rusefi/issues/8037)

changes:
* removed E0 curve
* `CUSTOM_ERR_ZERO_E0_MULT` is now unused
* renamed `coolantTemperatureCoefficient` for more correct `E85Coefficient`
* E85 cranking now interpolates between 1 and the value of the (E85) curve
* new tests for E85 on cranking

LCOV:
image

@ElDominio suggest on the tickets that we can also remove the E85 curve and change to a single field multiplier, so open question if I should remove that on a separate PR to close #8037 issue or not

### CODE REVIEW

File: firmware/config/engines/mazda/mazda_miata_1_6.cpp [hunk 1]
```diff
@@ -164,22 +164,23 @@ void miataNAcommonEngineSettings() {
...
+	//config->crankingFuelCoef[4] = 1.0;
 	config->crankingFuelBins[4] = 35;
-	config->crankingFuelCoef[5] = 1.0;
+	//config->crankingFuelCoef[5] = 1.0;
 	config->crankingFuelBins[5] = 50;
-	config->crankingFuelCoef[6] = 1.0;
+	//config->crankingFuelCoef[6] = 1.0;
 	config->crankingFuelBins[6] = 65;
-	config->crankingFuelCoef[7] = 1.0;
+	//config->crankingFuelCoef[7] = 1.0;
```
Comment (rusefillc) [inline firmware/config/engines/mazda/mazda_miata_1_6.cpp:183]: dead code not nice

it looks like we want to kills some legacy mazda preset values, let's do this in separate preparation PR @FDSoftware ?

**Comment by rusefillc** [comment]
ooops I did not mean to merge this sorry

https://github.com/rusefi/rusefi/pull/8209
