### PR TITLE
fix CRC errors

### LINKED ISSUE #1943: occasional tunerstudio CRC errors
I see about 1 CRC error per second when TS is updating at ~100hz.

I'm pretty sure what's happening is that another thread is preempting the TS thread during the CRC calculation, and that other thread happens to write the output channel struct.  Then when the packet is sent, the CRC doesn't match the data!

### PR DESCRIPTION
**Pull request by mck1117**
use the `crcReadBuffer` as a transmit buffer as well.  This ensures that we compute the CRC and transmit the same data - there's no opportunity for another thread to preempt and change the data between the CRC calculation and transmission.  This might actually net improve performance - it saves two calls to `sr5WriteData`.

fixes #1943

### CODE REVIEW

File: firmware/console/binary/tunerstudio_io.cpp [hunk 1]
```diff
@@ -245,20 +242,34 @@ void sr5WriteCrcPacket(ts_channel_s *tsChannel, const uint8_t responseCode, cons
 	}
 #endif /* TS_CAN_DEVICE */
 
-	*(uint16_t *) writeBuffer = SWAP_UINT16(size + 1);   // packet size including command
-	*(uint8_t *) (writeBuffer + 2) = responseCode;
+	auto scratchBuffer = tsChannel->crcReadBuffer;
```
Comment (rusefillc) [inline firmware/console/binary/tunerstudio_io.cpp:245]: shall we rename 'crcReadBuffer' since at this point that's not really a 'read' buffer?

File: firmware/console/binary/tunerstudio_io.cpp [hunk 2]
```diff
@@ -245,20 +242,34 @@ void sr5WriteCrcPacket(ts_channel_s *tsChannel, const uint8_t responseCode, cons
...
+	}
 
-	*(uint32_t *) (crcBuffer) = SWAP_UINT32(crc);
+	// don't transmit too large a buffer
+	efiAssertVoid(OBD_PCM_Processor_Fault, size <= BLOCKING_FACTOR + 7, "sr5WriteCrcPacket tried to transmit too large a packet")
 
-	sr5WriteData(tsChannel, writeBuffer, 3);      // header
-	if (size > 0) {
-		sr5WriteData(tsChannel, (const uint8_t*)buf, size);      // body
+	// If transmitting data, copy it in to place in the scratch buffer
```
Comment (rusefillc) [inline firmware/console/binary/tunerstudio_io.cpp:255]: shall we change to "If transmitting data, copy it in to place in the scratch buffer to make sure that we calculate CRC of the immutable copy"

File: firmware/console/binary/tunerstudio_io.cpp (hunk 1 above)
Comment (mck1117) [reply firmware/console/binary/tunerstudio_io.cpp]: good idea!

File: firmware/console/binary/tunerstudio_io.cpp (hunk 2 above)
Comment (mck1117) [reply firmware/console/binary/tunerstudio_io.cpp:255]: good idea!

**Comment by mck1117** [comment]
fun testing: this has been sitting at 5k rpm for over an hour with exactly 0 `pcCrcFailureCount`

**Comment by rusefillc** [comment]
@mck1117 this bugfix is probably worth being mentioned in changelog?

**Comment by rusefillc** [comment]
@mck1117 

after 30 builds today build 1299 has just failed with

```
     [java] java.lang.IllegalStateException: Failed Got 10667.0 while trying to stay at 16000 after 13 seconds
     [java] 	at com.rusefi.AutoTest.lambda$static$0(AutoTest.java:68)
     [java] 	at com.rusefi.AutoTest.assertRpmDoesNotJump(AutoTest.java:107)
     [java] 	at com.rusefi.AutoTest.testV12(AutoTest.java:85)
     [java] 	at com.rusefi.AutoTest.mainTestBody(AutoTest.java:49)
     [java] 	at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:100)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:60)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:50)
     [java] 	at com.rusefi.RealHwTest.main(RealHwTest.java:33)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:861)
```
